MODEL:
  TYPE: vssm
  NAME: vssm_tiny_share_ssm
  DROP_PATH_RATE: 0.2
  VSSM:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 9, 2 ]
    D_STATE: 16
    DT_RANK: "auto"
    SSM_RATIO: 2.0
    MLP_RATIO: 0.0
    DOWNSAMPLE: "v1"
    SHARED_SSM: true # do not recognize True @^@